#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_LINQ_SP_MVC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="crud")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["crudConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EMP")]
		public ISingleResult<SP_EMPResult> SP_EMP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMID", DbType="Int")] System.Nullable<int> eMID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMNAME", DbType="NVarChar(150)")] string eMNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMAIL", DbType="NVarChar(150)")] string eMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SALARY", DbType="Int")] System.Nullable<int> sALARY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CRUDOPTION", DbType="NVarChar(50)")] string cRUDOPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eMID, eMNAME, eMAIL, sALARY, cRUDOPTION);
			return ((ISingleResult<SP_EMPResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_EMPResult
	{
		
		private int _EMID;
		
		private string _EMNAME;
		
		private string _EMAIL;
		
		private System.Nullable<int> _SALARY;
		
		public SP_EMPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMID", DbType="Int NOT NULL")]
		public int EMID
		{
			get
			{
				return this._EMID;
			}
			set
			{
				if ((this._EMID != value))
				{
					this._EMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMNAME", DbType="NVarChar(150)")]
		public string EMNAME
		{
			get
			{
				return this._EMNAME;
			}
			set
			{
				if ((this._EMNAME != value))
				{
					this._EMNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(150)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALARY", DbType="Int")]
		public System.Nullable<int> SALARY
		{
			get
			{
				return this._SALARY;
			}
			set
			{
				if ((this._SALARY != value))
				{
					this._SALARY = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
