CREATE PROCEDURE SP_EMP
@EMID INT = NULL,
@EMNAME NVARCHAR(150) = NULL,
@EMAIL NVARCHAR(150) = NULL,
@SALARY INT,
@CRUDOPTION NVARCHAR(50) = NULL
AS
BEGIN
	IF(@CRUDOPTION = 'SELECT')
	BEGIN
		SELECT * FROM EMPLOYEE
	END
	IF(@CRUDOPTION = 'DETAILS')
	BEGIN
		SELECT * FROM EMPLOYEE WHERE EMID=@EMID
	END
	IF(@CRUDOPTION = 'INSERT')
	BEGIN
		INSERT INTO EMPLOYEE VALUES (@EMNAME, @EMAIL, @SALARY)
	END
	IF(@CRUDOPTION = 'UPDATE')
	BEGIN
		UPDATE EMPLOYEE SET EMNAME=@EMNAME, EMAIL=@EMAIL, SALARY=@SALARY WHERE EMID = @EMID
	END
	IF(@CRUDOPTION = 'DELETE')
	BEGIN
		DELETE FROM EMPLOYEE WHERE EMID = @EMID
	END
END